### ISSUE TITLE
不已管理员身份运行直接报错

### ISSUE THREAD

**Issue by libotao-github** [triwinds/ns-emu-tools#1]
![image](https://user-images.githubusercontent.com/53339584/198869575-02268df0-247e-407f-973f-192f59a517de.png)

**Comment by triwinds** [comment]
`windir` 是个特殊的目录，正常的权限是不能在这个目录里面直接写入的，把 exe 放到其他普通的目录下运行就好了

**Comment by libotao-github** [comment]
![image](https://user-images.githubusercontent.com/53339584/198870120-75094c35-197d-458c-8082-2990e50c8db2.png)

**Comment by libotao-github** [comment]
下载固件的时候如果中断或者网络超时页面会卡死

**Comment by libotao-github** [comment]
写的蛮好，牛

**Comment by triwinds** [comment]
> ![image](https://user-images.githubusercontent.com/53339584/198870120-75094c35-197d-458c-8082-2990e50c8db2.png)

可以把 `yuzu-tools.log` 这个文件贴上来看一下吗？现在 archive.org 是在检测到有系统代理的时候会直连访问，没开系统代理的情况应该是用的 cf 反代的

**Comment by libotao-github** [comment]
![image](https://user-images.githubusercontent.com/53339584/198870436-fa5f3073-dc44-4444-a204-35894bb0646b.png)

**Comment by libotao-github** [comment]
![image](https://user-images.githubusercontent.com/53339584/198870445-3df81acf-eb8a-4a0b-ad97-0d6aa23b200b.png)

**Comment by libotao-github** [comment]
我是开了代理不行，不开反而可以，我有个问题想请教一下，你这个打包exe是用的什么？

**Comment by triwinds** [comment]
有些代理软件不能正确的设置系统代理，所以 python 一些底层的 lib 会出问题。

打包用的 pyinstaller , 打包过程详见 https://github.com/triwinds/ns-emu-tools/blob/main/.github/workflows/ci-build.yaml

**Comment by libotao-github** [comment]
> 因此，python 不能代理软件的一些正确设置的系统库会出问题。
> 
> 打包用的pyinstaller，打包过程https://github.com/triwinds/ns-emu-tools/blob/main/.github/workflows/ci-build.yaml

顺便提一个小小的建议，加上ip阈值限制策略，不然无论用的免费云还是什么很快流量会被干完和限速，谢谢你，很牛，敢为人先和分享

**Comment by libotao-github** [comment]
> 因此，python 不能代理软件的一些正确设置的系统库会出问题。
> 
> 打包用的pyinstaller，打包过程https://github.com/triwinds/ns-emu-tools/blob/main/.github/workflows/ci-build.yaml

顺便提一个小小的建议，加一下ip阈值限制策略，无论是用的免费云还是付费云，被一些别有用心之人乱下载一下流量就会被搞完和限速，谢谢你，很牛，敢为人先和善于分享
