### ISSUE TITLE
建议将suyu升级加进去。

### ISSUE THREAD

**Issue by TisonTian** [triwinds/ns-emu-tools#103]
供大佬参考

**Comment by gchuyun** [comment]
同求

**Comment by triwinds** [comment]
https://github.com/triwinds/ns-emu-tools/actions/runs/8468079555

这个版本里先实现了 suyu 相关的一些基础功能， 模拟器版本检测因为 tag 和应用中显示的版本不一致，所以这个版本先不做。

**Comment by RUANRUI1995** [comment]
> > https://github.com/triwinds/ns-emu-tools/actions/runs/8468079555
> > 这个版本里先实现了 suyu 相关的一些基础功能， 模拟器版本检测因为 tag 和应用中显示的版本不一致，所以这个版本先不做。
> 
> 可否做一个user目录迁移功能？做一个按钮，点击按钮后自动将yuzu安装目录中的user子目录复制到suyu安装目录中（已测试可用）。 点击按钮后可以弹出一个确认框防止误操作，在进行复制操作前可以预先执行一些检测操作，例如检测目标路径是否存在“user”目录，存在则不进行复制并向用户弹出提示。

可以使用windows cmd自带的mklink /d 命令，建立文件夹链接，亲测

**Comment by Gokou-Ruri** [comment]
> > > https://github.com/triwinds/ns-emu-tools/actions/runs/8468079555
> > > 这个版本里先实现了 suyu 相关的一些基础功能， 模拟器版本检测因为 tag 和应用中显示的版本不一致，所以这个版本先不做。
> > 
> > 
> > 可否做一个user目录迁移功能？做一个按钮，点击按钮后自动将yuzu安装目录中的user子目录复制到suyu安装目录中（已测试可用）。 点击按钮后可以弹出一个确认框防止误操作，在进行复制操作前可以预先执行一些检测操作，例如检测目标路径是否存在“user”目录，存在则不进行复制并向用户弹出提示。
> 
> 可以使用windows cmd自带的mklink /d 命令，建立文件夹链接，亲测

软链接我知道，但这个功能主要是为了省去手动打开两个安装目录复制的麻烦（类似自动重命名yuzu.exe为cemu.exe那样），以及避免破坏原本yuzu的配置文件。
suyu后期会不会大改yuzu的代码谁也不清楚，所以直接软链接有可能会导致以后yuzu无法正常读取user目录里的文件。

**Comment by triwinds** [comment]
Fixed in 0.4.8
