### ISSUE TITLE
无法下载固件

### ISSUE THREAD

**Issue by 1753157217** [triwinds/ns-emu-tools#105]
固件下载栏是空的
![Cache_70b229cb2867e7c7](https://github.com/triwinds/ns-emu-tools/assets/56900837/b0d242b4-d219-4807-aa1b-7a38e85ac0fc)

**Comment by Gokou-Ruri** [comment]
> 试试这个版本： https://github.com/triwinds/ns-emu-tools/actions/runs/8468079555

确实已修复，感谢。

**Comment by triwinds** [comment]
> > 试试这个版本： https://github.com/triwinds/ns-emu-tools/actions/runs/8468079555
> 
> 确实已修复固件下载功能，但固件检测功能仍然失效（失效好久了XD）。 当更新固件后，能正常显示固件版本，但点击版本号检测版本，检测完成后，版本号会变成“未知”。 `开始扫描固件文件...` `固件版本检测完成`
> 
> 3个模拟器都是这个情况。

hactool 不能识别非英文的路径，现在换成了 nsz 去解析固件，试试这个
https://github.com/triwinds/ns-emu-tools/actions/runs/8589530063

**Comment by triwinds** [comment]
Fixed in 0.4.8
