### ISSUE TITLE
suyu新版本0.03下载失败，需要手动下载解压，是文件命名规格的问题

### ISSUE THREAD

**Issue by Tacrine** [triwinds/ns-emu-tools#107]
未找到 Suyu [v0.0.3] 对应的 Windows 安装包
No windows package found for tag v0.0.3

**Comment by triwinds** [comment]
先试试这个吧：
https://github.com/triwinds/ns-emu-tools/actions/runs/8662807465

**Comment by triwinds** [comment]
Fixed in 0.4.9

**Comment by Tacrine** [comment]
老哥厉害，感谢
