### ISSUE TITLE
软件启动窗口

### ISSUE THREAD

**Issue by AvalonPlus** [triwinds/ns-emu-tools#15]
之前启动时，软件有独立的窗口，现在是启动时会自动弹开默认浏览器，通过浏览器窗口来操作软件，请问如何改回独立窗口
[changelog.md](https://github.com/triwinds/ns-emu-tools/files/10253368/changelog.md)

**Comment by triwinds** [comment]
用 webview 版本，或者装个 chrome 浏览器
