### ISSUE TITLE
系统睡眠唤醒后工具的主要功能都失效了

### ISSUE THREAD

**Issue by Femoon** [triwinds/ns-emu-tools#16]
包括但不限于启动yuzu，修改路径，打开yuzu文件夹等各种交互功能，控制台可正常打开但是没有新的日志打印出来

**Comment by triwinds** [comment]
看起来是系统睡眠后浏览器与 python 后端的 websocket 的连接被系统切断，然后 python 后端检测不到连接就自动退出了。
彻底解决的话需要更换整个框架，这个比较麻烦；临时解决的话可以在 ws 连接断开后在前端弹出一个重启程序的提示，这个下一个版本里面会加上。

**Comment by Femoon** [comment]
> 看起来是系统睡眠后浏览器与 python 后端的 websocket 的连接被系统切断，然后 python 后端检测不到连接就自动退出了。 彻底解决的话需要更换整个框架，这个比较麻烦；临时解决的话可以在 ws 连接断开后在前端弹出一个重启程序的提示，这个下一个版本里面会加上。

辛苦大佬了，解决方案也挺好的👍

**Comment by triwinds** [comment]
Fixed in 0.2.4
