### ISSUE TITLE
金手指问题

### ISSUE THREAD

**Issue by fantasyjqc** [triwinds/ns-emu-tools#19]
如果yuzu的mod目录和yuzu的安装目录不在一起的话，好像无法识别，这个要如何解决呢？

**Comment by triwinds** [comment]
按理来说 yuzu 的 load 目录是会从 qt-config.ini 里面自动获取的，是有多个 yuzu 模拟器吗？

方便的话发一下 ns-emu-tools.log 这个日志？

**Comment by fantasyjqc** [comment]
[ns-emu-tools.log](https://github.com/triwinds/ns-emu-tools/files/10524286/ns-emu-tools.log)

我目前是把模拟器放在C:\Games\emulators\yuzu，工具是放在C:\Users\Administrator\Desktop\Games\NsEmuTools

mod目录是在模拟器中设置的Mod加载根目录为：D:/switch/mod/

**Comment by triwinds** [comment]
Fixed in 0.2.6

**Comment by fantasyjqc** [comment]
> Fixed in 0.2.6

这个问题似乎并没有解决，我升级到0.2.6之后依然是提示no database，是我的放置位置不正确吗？求大佬指导放置位置。

![image](https://user-images.githubusercontent.com/4988150/216259747-b161d16d-fb8d-47e5-b3dd-ff1de777ce15.png)


[ns-emu-tools.log](https://github.com/triwinds/ns-emu-tools/files/10566254/ns-emu-tools.log)

**Comment by triwinds** [comment]
> 2023-02-02 15:25:06.971|INFO|module.yuzu|yuzu.py:243|get_yuzu_load_path|use load path from yuzu config: D:\switch\mod
> 2023-02-02 15:25:06.972|INFO|module.cheats|cheats.py:32|scan_all_cheats_folder|scanning cheats under path: D:\switch\mod

看起来已经能获取到 mod 所在的文件夹了。金手指文件需要放在 cheats 文件夹里面，文件名应该是 16 位地址的 txt, 满足这两个条件才会出现在列表里面。

例如这个样子，具体的可以在 B 站里面找找 yuzu 金手指的教程。

![image](https://user-images.githubusercontent.com/7413161/216330626-ec389511-aa71-4b8f-9259-eca4e8c13f21.png)
