### ISSUE TITLE
路径问题

### ISSUE THREAD

**Issue by gramra** [triwinds/ns-emu-tools#20]
可以弄个保存路径吗！每次切换分支都要改路径 就怕哪天改错了.....

**Comment by triwinds** [comment]
ok

**Comment by triwinds** [comment]
Fixed in 0.2.6

**Comment by WanderMax** [comment]
想问问，能否把每个分支的路径单独出来，比如mt 对应一个，ea对应一个

**Comment by triwinds** [comment]
建几个文件夹就可以了吧，比如 D:\yuzu_ea, D:\yuzu_mainline 这样。

各个文件夹的相关信息 (分支，版本) 也是会一并保存的，直接在下拉框里面选就行了

**Comment by WanderMax** [comment]
这个号好，回去更新一下就这么浓
