### ISSUE TITLE
Ryujinx Portable 使用工具更新會把 Portable 目錄清空...

### ISSUE THREAD

**Issue by naukhiav** [triwinds/ns-emu-tools#23]
YUZU 的 USER 目錄沒事,但 Ryujinx 的 Portable 被刪了,

**Comment by triwinds** [comment]
https://github.com/triwinds/ns-emu-tools/blob/a136acce44f7fed985bd1567007cd50304df8087/module/ryujinx.py#L106-L111

按理说 portable 文件夹应该是不会被删除的，方便看一下 ns-emu-tools.log 日志里 removing path 的相关内容吗？

**Comment by naukhiav** [comment]
昨天升的版本,印像中之前也有用過這工具升級,昨天升完發現 Portable 目錄不見了,想說好吧,重設目錄,重下固件,反正也沒啥遊戲 save ,結果又提示已有固件,無法下載....只好用 Ryujinx 自身安裝固件.... 
    在 2023年2月1日 星期三 下午08:11:37 [GMT+8]， ***@***.***> 寫道：  
 
 


https://github.com/triwinds/ns-emu-tools/blob/a136acce44f7fed985bd1567007cd50304df8087/module/ryujinx.py#L106-L111

按理说 portable 文件夹应该是不会被删除的，方便看一下 ns-emu-tools.log 日志里 removing path 的相关内容吗？

**Comment by triwinds** [comment]
我这里无法复现这个问题，能上传一下 ns-emu-tools.log 这个文件吗？

**Comment by naukhiav** [comment]
昨天回覆時不是有傳附件?
链接: https://pan.baidu.com/s/1Cav74pstz7kbSxEVoboSNg?pwd=6a3d 提取码: 6a3d 复制这段内容后打开百度网盘手机App，操作更方便哦

    在 2023年2月2日 星期四 下午09:01:15 [GMT+8]， ***@***.***> 寫道：  
 
 


我这里无法复现这个问题，能上传一下 ns-emu-tools.log 这个文件吗？

**Comment by triwinds** [comment]
邮件里的附件会被 GitHub 无视掉...

> 2023-02-01 01:08:17.142|DEBUG|module.ryujinx|ryujinx.py:111|clear_ryujinx_folder|removing path: E:\games\Switch\ryujinx\publish\Portable

看起来是目录大小写的问题，这个 bug 下个版本会修掉

**Comment by triwinds** [comment]
Fixed in 0.2.7
