### ISSUE TITLE
安装时C盘文件夹拒绝访问

### ISSUE THREAD

**Issue by YHFdddd** [triwinds/ns-emu-tools#25]
[](url)
[aria2.log](https://github.com/triwinds/ns-emu-tools/files/10607672/aria2.log)
[ns-emu-tools.log](https://github.com/triwinds/ns-emu-tools/files/10607673/ns-emu-tools.log)

**Comment by triwinds** [comment]
> PermissionError: [WinError 5] 拒绝访问。: 'C:\\Users\\Administrator\\AppData\\Local\\Temp\\yuzu-windows-msvc-early-access\\yuzu.exe'

这个文件可能被什么程序占用住了，导致无法进行删除，重启一下系统试试？

**Comment by YHFdddd** [comment]
>
