### ISSUE TITLE
升级到最新版后就一直白屏 无法显示

### ISSUE THREAD

**Issue by tarcy118** [triwinds/ns-emu-tools#26]
升级到最新版后就一直白屏 无法显示
![sshot-1](https://user-images.githubusercontent.com/124449048/216774083-3b38a5cc-4b83-40e4-88e0-7a6bb39eb5ef.png)

**Comment by tarcy118** [comment]
请求不要合并WebView2显示，还是像以前一样吧，我这WebView2显示不出来，以前一直用调用网页的没问题!!

**Comment by triwinds** [comment]
发一下 ns-emu-tools.log 这个日志？

另外把 config.json 这个文件里 setting/ui/mode 的值从 webview 改成 browser 可以回到之前的模式

**Comment by tarcy118** [comment]
[ns-emu-tools.log](https://github.com/triwinds/ns-emu-tools/files/10609019/ns-emu-tools.log)

**Comment by triwinds** [comment]
日志看起来是一切正常的，现在打开的界面还是白屏吗？

**Comment by triwinds** [comment]
0.2.8 这个版本会在启动之后在目录下创建一个 bat 脚本，可以用这个脚本将 ui 改回浏览器启动的模式。

这个 issue 我就先关了，如果还有问题的话可以重新打开它。
