### ISSUE TITLE
更新了最新版之后出错（0.3.8）

### ISSUE THREAD

**Issue by EdisonChen1024** [triwinds/ns-emu-tools#41]
更新后启动不了：
![image](https://user-images.githubusercontent.com/5506018/235894711-571d9010-ec2d-4da5-9ffa-123f5c901fa9.png)

切换UI为默认浏览器就正常：
![image](https://user-images.githubusercontent.com/5506018/235895003-3c063e72-691a-4044-9c37-d94be7abfcb5.png)

**Comment by triwinds** [comment]
可能是旧版本的程序还没有完全退出，然后新版本的程序启动时文件占用就出现了这个问题。
重启一下系统然后换 webview 模式再启动一下试试？
自动更新的脚本可能需要加一条强制关闭旧版本的程序的指令。

**Comment by triwinds** [comment]
Fixed in 0.3.9
