### ISSUE TITLE
新用户提几个小建议

### ISSUE THREAD

**Issue by alanleonhardt** [triwinds/ns-emu-tools#42]
1、固件能不能自行选择安装路径，实现不了安装前写个提醒自动安装到C盘也行。
2、模拟器的EA、主线版本能不能分开，或是用户点击版本按钮时路径自动切换。
3、金手指希望能有个全选、全不选的选项。

**Comment by triwinds** [comment]
1. 现在固件的安装路径是自动检测的，不需要自行选择(因为模拟器只认这些目录)。提醒倒是可以加一个。
检测逻辑是如果你模拟器目录下有 user/portable 文件夹或者在 yuzu 设置里面改过 nand 文件夹的地址，那么程序会优先使用这些路径，其次才是 c 盘的 appdata（如果有），如果模拟器目录里面和 appdata 里面都没有就会在模拟器目录自动创建对应的 user/portable 文件夹。

2. 这个可以直接在路径的下拉框里面改，具体可以参考 (#20 )

3. 这个可以有

**Comment by triwinds** [comment]
Fixed in 0.3.9
