### ISSUE TITLE
下载模拟器出现错误如下

### ISSUE THREAD

**Issue by feitong199** [triwinds/ns-emu-tools#45]
下载模拟器出现错误如下：

正在获取 ryujinx 版本信息...
开始下载 ryujinx ...
starting aria2 daemon at port 56095
如果遇到下载失败或卡住的问题, 可以尝试在设置中换个下载源, 如果还是不行就挂个梯子
如果你的网络支持 IPv6, 也可以尝试在设置中允许 aria2 使用 IPv6, 看看能不能解决问题
下载速度: 0.00 B/s, 0.00 B/0.00 B
文件已存在, 跳过下载.
清除旧版 ryujinx 文件...
出现异常, Traceback (most recent call last):
  File "api\ryujinx_api.py", line 79, in install_ryujinx
  File "module\ryujinx.py", line 67, in install_ryujinx_by_version
  File "zipfile.py", line 1269, in __init__
  File "zipfile.py", line 1336, in _RealGetContents
zipfile.BadZipFile: File is not a zip file
File is not a zip file

[ns-emu-tools.log](https://github.com/triwinds/ns-emu-tools/files/11414050/ns-emu-tools.log)

[aria2.log](https://github.com/triwinds/ns-emu-tools/files/11414051/aria2.log)

**Comment by triwinds** [comment]
Fixed in 0.3.9
