### ISSUE TITLE
软件打开白屏

### ISSUE THREAD

**Issue by Betrayal0214** [triwinds/ns-emu-tools#48]
最近几天才出现的，初步怀疑是win11内部预览版的bug,或因为我卸载了系统的预装软件
日志如下，求大佬帮帮，突然连win11搜索框和此电脑属性都打不开了，模拟器一切正常
[ns-emu-tools.log](https://github.com/triwinds/ns-emu-tools/files/11419577/ns-emu-tools.log)

Microsoft Windows 11 教育版 Build 22624 64 位
处理器：AMD Ryzen 7 3800X 8-Core Processor              x86 Family 15 Model 1 Stepping 0
内存：G-Skill（2133 MHz）；G-Skill（2133 MHz）；总共 2 根。共：16301MB （约16G）
显卡：NVIDIA GeForce RTX 2070 SUPER；总共 1 块。
主板：ASUSTeK COMPUTER INC.  ROG STRIX X570-F GAMING
显示器：屏幕分辨率：3840*2160 ； 色深：32（119Hz) ；
硬盘：Predator SSD GM7000 2TB；Samsung SSD 970 EVO Plus 250GB；WDC WD10EZEX-00MFCA0；总共3 块。
网卡：TAP-Windows Provider V9；Intel Corporation；Microsoft；Microsoft；Microsoft；Netease UU V9.21；总共 6 个。
电池：已接入电源：100%

**Comment by triwinds** [comment]
看起来是找不到 webview2 环境，之前的 0.3.8 版本能用吗？

**Comment by Betrayal0214** [comment]
之前的版本能用。似乎是系统的问题，重装后解决了，抱歉浪费了大佬的时间，谢谢

**Comment by triwinds** [comment]
系统重装后 0.3.9 正常吗？需要确认下是不是新版 pywebview 的问题

**Comment by triwinds** [comment]
Fixed in 0.4.0

**Comment by Betrayal0214** [comment]
重装后0.3.9正常   我这里从0.3.9到0.4.0一直无法记忆窗口大小

**Comment by triwinds** [comment]
记忆窗口大小这个功能只有在 webview 或者 chrome/edge 的 app 模式下启动才能正常工作，窗口大小发生改变后需要等 3s 才会写入配置文件
