### ISSUE TITLE
龙神ldn版本

### ISSUE THREAD

**Issue by hubGitp** [triwinds/ns-emu-tools#5]
后续龙神会添加ldn版本吗

**Comment by triwinds** [comment]
ldn 似乎没有什么能稳定获取历史版本的渠道，Ryujinx Wiki 里面只能拿到最近一个版本的下载地址。。。
如果没有什么办法拿到这些数据的话这个 issue 只能先挂着了

**Comment by triwinds** [comment]
Fixed in 0.2.4
