### ISSUE TITLE
打开时无法记忆上次的窗口大小

### ISSUE THREAD

**Issue by zivilyyyn** [triwinds/ns-emu-tools#50]
每次打开窗口都很小，拉大之后关闭，再次打开还是很小的窗口。
[ns-emu-tools.log](https://github.com/triwinds/ns-emu-tools/files/11431660/ns-emu-tools.log)

**Comment by triwinds** [comment]
可以先试试这个 ci build 的版本：
https://github.com/triwinds/ns-emu-tools/actions/runs/4948036966

**Comment by triwinds** [comment]
Fixed in 0.4.0

**Comment by zivilyyyn** [comment]
我还是不能保存窗口大小，不过看其他人视频里是可以的，估计是我电脑的问题

**Comment by triwinds** [comment]
这个功能只有在 webview 或者 chrome/edge 的 app 模式下启动才能正常工作，窗口大小发生改变后需要等 3s 才会写入配置文件

**Comment by zivilyyyn** [comment]
设置成浏览器模式启动就可以了，感谢。
