### ISSUE TITLE
yuzu版本无法检测，显示检测完成，但还是显示未知

### ISSUE THREAD

**Issue by Ptuer-swpu** [triwinds/ns-emu-tools#51]
[ns-emu-tools.log](https://github.com/triwinds/ns-emu-tools/files/11442874/ns-emu-tools.log)

**Comment by triwinds** [comment]
可以先试试这个 ci build 的版本：
https://github.com/triwinds/ns-emu-tools/actions/runs/4948036966

**Comment by triwinds** [comment]
Fixed in 0.4.0
