### ISSUE TITLE
扫描不到龙神固件位置

### ISSUE THREAD

**Issue by metaforget** [triwinds/ns-emu-tools#56]
作者你好，为什么这个扫描不到龙神模拟器固件位置，是因为我把龙神的目录从默认的C盘挪到启动exe同级portable文件夹导致的吗？

**Comment by metaforget** [comment]
@triwinds

**Comment by triwinds** [comment]
固件路径的选取有优先级判断，具体的逻辑看下面，Path(config.ryujinx.path) 就是你的 ryujinx 目录
![image](https://github.com/triwinds/ns-emu-tools/assets/7413161/cacd5e65-e42e-4338-9335-0631544de3ec)

**Comment by metaforget** [comment]
> 固定路径的选择取有优先级判断，具体的总专辑看下面，Path(config.ryujinx.path) 就是你的ryujinx目录 ![图像](https://user-images.githubusercontent.com/7413161/238171616-cacd5e65-e42e-4338-9335-0631544de3ec.png)

现在我想扫描固件版本，控制台日志只是提示开始扫描，然后一直没反应了

**Comment by metaforget** [comment]
![image](https://github.com/triwinds/ns-emu-tools/assets/97219459/d10f11ab-b2c1-4c5e-bff0-f8099fc88dc6)

**Comment by triwinds** [comment]
看样子是没找到要解密的那个固件文件，你确定现在 ryujinx 里面的固件是可以被 ryujinx 正常识别的吗？

**Comment by metaforget** [comment]
@triwinds 能用的，是16.0.3版，我是解压固件zip文件夹，龙神安装固件选择固件文件夹位置
