### ISSUE TITLE
可以记忆上次设置的窗口大小吗？

### ISSUE THREAD

**Issue by yw2048** [triwinds/ns-emu-tools#58]
之前的窗口大小挺好的，现在最新版窗口太小了，这次调节好了下次打开又会恢复到很小的窗口状态

**Comment by triwinds** [comment]
这个功能在 0.4.0 应该就已经支持了，上传一下日志？

**Comment by yw2048** [comment]
> 这个功能在 0.4.0 应该就已经支持了，上传一下日志？

我就是更新0.4.0之后不能了，之前好像可以
[aria2.log](https://github.com/triwinds/ns-emu-tools/files/11524034/aria2.log)
[ns-emu-tools.log](https://github.com/triwinds/ns-emu-tools/files/11524035/ns-emu-tools.log)

**Comment by triwinds** [comment]
你是系统的显示设置里面开了缩放吗？
![image](https://github.com/triwinds/ns-emu-tools/assets/7413161/9f0267fb-d832-4f3f-bbba-6a4762358f21)

**Comment by yw2048** [comment]
> 你是系统的显示设置里面开了缩放吗？ ![image](https://user-images.githubusercontent.com/7413161/239738134-9f0267fb-d832-4f3f-bbba-6a4762358f21.png)

对的，但是这没什么影响吧，我每次改完再打开窗口又变回默认了

**Comment by triwinds** [comment]
有的，这样 js 拿到的 size 是不正确的。
试试看这个 ci build: https://github.com/triwinds/ns-emu-tools/actions/runs/5038324838

**Comment by yw2048** [comment]
> 有的，这样 js 拿到的 size 是不正确的。 试试看这个 CI build： https://github.com/triwinds/ns-emu-tools/actions/runs/5038324838

窗口确实变大了，但是仍然不能记录上次退出时的窗口大小

**Comment by triwinds** [comment]
浏览器和 webview 的行为还不一样...
再试试这个吧：
https://github.com/triwinds/ns-emu-tools/actions/runs/5046746679

**Comment by yw2048** [comment]
> 浏览器和 webview 的行为还不一样... 再试试这个吧： https://github.com/triwinds/ns-emu-tools/actions/runs/5046746679

现在会记录了，但比上次关闭时的窗口小一点点。
关闭前：
![关闭前](https://github.com/triwinds/ns-emu-tools/assets/89087607/a97d01e0-1f15-4638-b123-5704b3be3403)
再次打开：
![再次打开](https://github.com/triwinds/ns-emu-tools/assets/89087607/b8154856-2b1f-4838-b307-acb70c72a15e)
我没有动鼠标的滚轮

**Comment by triwinds** [comment]
再试试这个？
https://github.com/triwinds/ns-emu-tools/actions/runs/5047992254

**Comment by yw2048** [comment]
> 再试试这个？ https://github.com/triwinds/ns-emu-tools/actions/runs/5047992254
可以了，很完美了

**Comment by triwinds** [comment]
Fixed in 0.4.1
