### ISSUE TITLE
打开nsemutools.exe文件时显示"failed to execute script "main_devnull" due to unhandled exception

### ISSUE THREAD

**Issue by sorrowise** [triwinds/ns-emu-tools#59]
请在描述问题的同时上传 ns-emu-tools.log 这个文件。
如果问题与 aria2 下载有关，请将 aria2.log 这个文件也带上。

[ns-emu-tools.log](https://github.com/triwinds/ns-emu-tools/files/11512514/ns-emu-tools.log)

![微信截图_20230519084602](https://github.com/triwinds/ns-emu-tools/assets/8664162/6f6c6260-2e63-4317-b6ff-0ce6b52f56df)

**Comment by triwinds** [comment]
看上去是代理软件的问题，可以试试关掉代理或者换一个支持 http 代理的代理软件
