### ISSUE TITLE
Support portable version of yuzu

### ISSUE THREAD

**Issue by RivenNero** [triwinds/ns-emu-tools#64]
Change yuze to the portable version by creating a new folder named user in the directory of the yuze executable.

Reference Links:
https://www.reddit.com/r/NewYuzuPiracy/comments/13gh9ts/yuzu_totk_complete_setup_guide_60_fps_cutscenes/

**Comment by triwinds** [comment]
Already supported:
https://github.com/triwinds/ns-emu-tools/blob/e7f623541aa11d0df3949f494211e181db384a0a/module/yuzu.py#L198-L204
