### ISSUE TITLE
Change file name

### ISSUE THREAD

**Issue by RivenNero** [triwinds/ns-emu-tools#65]
yuze only needs the file prod.keys, title.keys is needed for other simulators.

This automatically created txt file is in the keys folder:

![1](https://github.com/triwinds/ns-emu-tools/assets/35187885/11225882-8a8f-4c1b-b27e-e3845a348064)

**Comment by triwinds** [comment]
According to the official guide, the title.keys is still needed: 
![image](https://github.com/triwinds/ns-emu-tools/assets/7413161/dbe37f67-690c-47fb-a36f-9772c7780eee)
