### ISSUE TITLE
0.4.1 安装更新问题

### ISSUE THREAD

**Issue by dongnishushu** [triwinds/ns-emu-tools#69]
新版更新 Yuzu 版本的时候检查 Yuzu 模拟器目录的占用状态，一直无法更新，重启电脑马上尝试更新都会提示已经被占用，建议还是不要添加这个功能了。

**Comment by triwinds** [comment]
你是将 NsEmuTools.exe 放到了模拟器目录下吗？

**Comment by dongnishushu** [comment]
WOW，一下就猜到，应该就是这个原因了吧，明天试试，谢谢🙏

发自我的 iPhone

在 2023年5月27日，22:55，triwinds ***@***.***> 写道：

﻿

你是将 NsEmuTools.exe 放到了模拟器目录下吗？

**Comment by triwinds** [comment]
Fixed in 0.4.2
