### ISSUE TITLE
0.4.1安装最新yuzu的时候提示目录被占用

### ISSUE THREAD

**Issue by ckjruanwu** [triwinds/ns-emu-tools#70]
如题，首先，nstools我是放在桌面的，即c盘，yuzu模拟器的文件夹放在d盘，更新的时候显示目录被占用，但是这两个文件夹我都放不同的盘了，我重启电脑，重启nstools，都没用，都提示被占用，昨天用的时候是可以正常更新的，只是今天更新到了0.4.1就这样了，而且我在任务管理器中看了，也没有任何关于yuzu的进程，顺带一问，那个ns-emu-tools.log文件是只需要把文件拖动到这个框里就好了嘛，我就这样拖了一下，不知道作者大大能不能看到
[ns-emu-tools.log](https://github.com/triwinds/ns-emu-tools/files/11583516/ns-emu-tools.log)

**Comment by triwinds** [comment]
先试试这个吧：
https://github.com/triwinds/ns-emu-tools/actions/runs/5102083770

**Comment by triwinds** [comment]
Fixed in 0.4.2
