### ISSUE TITLE
模拟器与固件无法显示最新版

### ISSUE THREAD

**Issue by henuoxi** [triwinds/ns-emu-tools#72]
[ns-emu-tools.log](https://github.com/triwinds/ns-emu-tools/files/11641768/ns-emu-tools.log)
[aria2.log](https://github.com/triwinds/ns-emu-tools/files/11641769/aria2.log)

**Comment by triwinds** [comment]
> requests.exceptions.SSLError: HTTPSConnectionPool(host='archive.org', port=443): Max retries exceeded with url: /download/nintendo-switch-global-firmwares/nintendo-switch-global-firmwares_files.xml (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)')))

你本地的证书出问题了，跑一下系统更新吧。
如果开了梯子或者系统里有 mitm 类型的审计也可以先关掉这些软件再试试。
