### ISSUE TITLE
yuzu模拟器安装好之后无法打开

### ISSUE THREAD

**Issue by ENDLESSZ** [triwinds/ns-emu-tools#76]
请在描述问题的同时上传 ns-emu-tools.log 这个文件。
如果问题与 aria2 下载有关，请将 aria2.log 这个文件也带上。
(将文件拖拽至输入框内即可)
[ns-emu-tools.log](https://github.com/triwinds/ns-emu-tools/files/12040013/ns-emu-tools.log)
下载过程中没有报错，但是之后打开不了。双击.exe文件，之后会弹出窗口，但界面完全是空白的，并且在几秒之后就会直接闪退，不报任何错误。

**Comment by triwinds** [comment]
是新版的 yuzu 打不开么？检查一下你的 msvc 是不是新版本的？

win + R 然后输入 cmd, 然后用下面的命令可以查看现在用的 msvc 是什么版本的

```bat
reg query HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\VisualStudio\14.0\VC\Runtimes\X64
```

**Comment by triwinds** [comment]
emmm 这个msvc 版本应该没什么问题。你的 yuzu 有改过什么配置吗？yuzu 文件夹下面建一个 user 文件夹试试？

**Comment by ENDLESSZ** [comment]
之前装过老版的yuzu，后来发现识别不了王国之泪就给卸载了，我印象里好像没改过啥。
刚试了yuzu文件下新建一个user，这次能显示这个界面。
但是我之前刚安装好的时候是按提示安装好两个.keys文件的。
![捕获](https://github.com/triwinds/ns-emu-tools/assets/56312249/8dad755c-0b94-431e-9724-0d0c7675e185)

**Comment by triwinds** [comment]
那应该是你之前加了什么奇怪的配置导致的，你原来的配置在 C:\Users\computer\AppData\Roaming\yuzu\，这个配置无法启动。
现在的配置在 yuzu 下的 user 文件夹，重新配一下固件和 key 就好了。
