### ISSUE TITLE
Ryujinx 更新日志加载报错

### ISSUE THREAD

**Issue by RUANRUI1995** [triwinds/ns-emu-tools#79]
请在描述问题的同时上传 ns-emu-tools.log 这个文件。
如果问题与 aria2 下载有关，请将 aria2.log 这个文件也带上。
(将文件拖拽至输入框内即可)
[ns-emu-tools.log](https://github.com/triwinds/ns-emu-tools/files/12393149/ns-emu-tools.log)

**Comment by triwinds** [comment]
Fixed in 0.4.3
