### ISSUE TITLE
金手指管理不识别文件软链接

### ISSUE THREAD

**Issue by Zhangxxl** [triwinds/ns-emu-tools#80]
我同时使用yuzu 和 Ryujinx, 同时管理两份mod和存档比较麻烦, 我就把存档和mod用文件软链接的形式,放到其他文件夹,在建立软链接到yuzu和ryujinx文件夹内, 打开 yuzu和ryujinx 都能识别到mod和金手指, 但是ns emu tools的金手指管理却识别不到

**Comment by triwinds** [comment]
这个文件软链接是怎么创建的？ 试了下 `mklink /d /j` 创建的链接是可以正常识别的啊...

**Comment by Zhangxxl** [comment]
只加了/d  没加/j，现在试了加了/j确实可以识别了
