### ISSUE TITLE
emu tools无法打开 切换ui启动方式也不行（我之前卸载了自带edge浏览器）

### ISSUE THREAD

**Issue by geinz** [triwinds/ns-emu-tools#86]
请在描述问题的同时上传 ns-emu-tools.log 这个文件。
如果问题与 aria2 下载有关，请将 aria2.log 这个文件也带上。
(将文件拖拽至输入框内即可)
[ns-emu-tools.log](https://github.com/triwinds/ns-emu-tools/files/13202089/ns-emu-tools.log)
![Snipaste_2023-10-30_15-33-11](https://github.com/triwinds/ns-emu-tools/assets/60915334/828a02f0-0831-4676-af60-7124d153e518)

**Comment by geinz** [comment]
https://github.com/triwinds/ns-emu-tools/assets/60915334/e579428f-a463-45b1-83b4-7d4de7b96d85

**Comment by geinz** [comment]
> 应该是 json 的数据结构出了点问题，试试这个版本？ https://github.com/triwinds/ns-emu-tools/actions/runs/6707943448 先删掉原来的 config.json，然后再改 ui 启动方式

这个版本正常使用，感谢~

**Comment by triwinds** [comment]
Fixed in 0.4.5
