### ISSUE TITLE
最新版本在Windows10系统下，软件界面错乱、显示不完整。

### ISSUE THREAD

**Issue by TopBiz** [triwinds/ns-emu-tools#87]
![50f9df42fbf2b211776fdf798c8065380dd78e83](https://github.com/triwinds/ns-emu-tools/assets/50977690/aa595709-3a07-417b-a3d5-2f39800f5f82)

**Comment by TopBiz** [comment]
求各位大神帮忙，谢谢。

**Comment by TopBiz** [comment]
@triwinds @RonaldinhoL  @chiyuki0325

**Comment by triwinds** [comment]
可能需要更新一下你的 webview 或者浏览器

**Comment by TopBiz** [comment]
[ns-emu-tools.log](https://github.com/triwinds/ns-emu-tools/files/13771491/ns-emu-tools.log)

**Comment by TopBiz** [comment]
@triwinds webview版本是120.0.2210.91   EDGE跟CHROME都是最新版。

**Comment by TopBiz** [comment]
@triwinds  用切换UI试过了EDGE、CHROME、WEBVIEW，都不行，都是界面错乱，实在找不到怎么解决了，求帮忙，求解决。谢谢

**Comment by triwinds** [comment]
能用浏览器打开然后 f12 看看有什么异常吗？

**Comment by TopBiz** [comment]
![Uploading 微信图片_20231226205725.png…]()

**Comment by TopBiz** [comment]
![1](https://github.com/triwinds/ns-emu-tools/assets/50977690/c5f1b383-7e08-4499-9374-7d6338851448)

**Comment by TopBiz** [comment]
![2](https://github.com/triwinds/ns-emu-tools/assets/50977690/a4e467db-5996-47cc-b890-426959f268a9)

**Comment by TopBiz** [comment]
![3](https://github.com/triwinds/ns-emu-tools/assets/50977690/b91448d7-6254-427a-bb12-0b1ad9a4fb8d)

**Comment by triwinds** [comment]
日志里看起来 css 文件好像少了几 kb
能看下你的 exe 的 md5 是什么吗？

```
D:\net>certutil -hashfile NsEmuTools.exe MD5
MD5 的 NsEmuTools.exe 哈希:
7bdef1ac38981d00b303ab948e34076a
CertUtil: -hashfile 命令成功完成。

D:\net>certutil -hashfile NsEmuTools-console.exe MD5
MD5 的 NsEmuTools-console.exe 哈希:
7fdfaa41952a92fb907328cc03ad5e3a
CertUtil: -hashfile 命令成功完成。
```

**Comment by TopBiz** [comment]
![4](https://github.com/triwinds/ns-emu-tools/assets/50977690/5e182864-383a-4404-8fca-be8027fb03af)

**Comment by TopBiz** [comment]
我在虚拟机环境下把assets下的css全部复制到宿主机下的assets文件夹下，刷新还是一样的问题。

**Comment by TopBiz** [comment]
一直没找到原因，今天只好重装系统了，装完系统以后软件是正常滴，但是我安装了一些平时能用到的软件以后，又完蛋了，这到底咋回事捏。。。@triwinds

**Comment by TopBiz** [comment]
@triwinds 貌似找到冲突软件了 Adobe Dreamweaver 8.0 卸载掉就可以了
