### ISSUE TITLE
yuzu固件和密钥文件夹指向可能不正确

### ISSUE THREAD

**Issue by TsukiNoKnight** [triwinds/ns-emu-tools#9]
似乎程序中直接找的是默认情况下的yuzu文件夹，但是当你在yuzu中设置了另外的nand和sdmc文件夹的时候(System/Filesystem)，固件和密钥似乎需要安装到这个设置的nand文件夹中而不是默认地址
当然这个自定义的nand文件夹地址是很好找到的，在%yuzu_home%/config/qt-config.ini中[Data%20Storage]/nand_directory条目能直接查到，如果不麻烦的话，希望做一下这个修改

**Comment by triwinds** [comment]
ok

**Comment by TsukiNoKnight** [comment]
我又看了一下，固件应该是放在nand文件夹下的，但是密钥是在%yuzu_home%根目录下，应该只需要修改固件的位置就可以了

**Comment by triwinds** [comment]
https://github.com/triwinds/ns-emu-tools/actions/runs/3547700343

改了一版，试一下吧。

**Comment by TsukiNoKnight** [comment]
非常好！没有问题！非常感谢！

**Comment by triwinds** [comment]
Fixed in 0.2.2
