### ISSUE TITLE
离线模式下报错 部分功能无法使用

### ISSUE THREAD

**Issue by kms9** [triwinds/ns-emu-tools#91]
请在描述问题的同时上传 ns-emu-tools.log 这个文件。
如果问题与 aria2 下载有关，请将 aria2.log 这个文件也带上。
(将文件拖拽至输入框内即可)

在断网之后 一直弹出对话框  掌机上使用的 

1. 
![image](https://github.com/triwinds/ns-emu-tools/assets/6856643/787b3761-20d7-4cdd-8240-4be30d0af291)
2. 
[ns-emu-tools.log](https://github.com/triwinds/ns-emu-tools/files/14080554/ns-emu-tools.log)

**Comment by triwinds** [comment]
断网之后重启程序能恢复吗？

**Comment by kms9** [comment]
不能 就一直提示错误

**Comment by triwinds** [comment]
web ui 需要允许访问 localhost 的连接，如果离线模式连本地 loopback 也会被禁用的话就没什么办法了😂

**Comment by kms9** [comment]
离线后本地好像 不会禁用 localhost吧 .. 不太了解这个问题...  目前我用了一个随身wifi... 变相解决了这个问题
