### ISSUE TITLE
能够显示安装，但是无法打开

### ISSUE THREAD

**Issue by ads4349** [triwinds/ns-emu-tools#92]
安装完成后，想要打开yuzu提示无法定位程序输入点于动态链接。无法定位的内容是yuzu.exe，即启动器。
[Uploading ns-emu-tools.log…]()

**Comment by triwinds** [comment]
应该是你的 vc++ runtime 太旧了

https://github.com/triwinds/ns-emu-tools/actions/runs/7726802309
这个版本里面增加了 msvc 的版本检测，更新 yuzu 后会自动检查 msvc 的版本，你试试看能不能解决问题

**Comment by ads4349** [comment]
感谢回复，尝试了下，还是不行，同样的报错

**Comment by ads4349** [comment]
[ns-emu-tools.log](https://github.com/triwinds/ns-emu-tools/files/14113995/ns-emu-tools.log)

**Comment by ads4349** [comment]
上次比较匆忙，这次又重新去修复了vc++ runtime，问题已经解决，多谢啦。
