### ISSUE TITLE
ryujinx切换不同分支路径最上面的分支不会变

### ISSUE THREAD

**Issue by RUANRUI1995** [triwinds/ns-emu-tools#96]
yuzu没这个问题，可以正常切换主线和EA。
ryujinx我是装了新老UI两个不同路径，切换的时候还要手动选分支。

{
  "yuzu_history": {
    "E:\\app\\yuzu": {
      "yuzu_path": "E:\\app\\yuzu",
      "yuzu_version": "1733",
      "yuzu_firmware": "17.0.1",
      "branch": "mainline"
    },
    "E:\\app\\yuzu_ea": {
      "yuzu_path": "E:\\app\\yuzu_ea",
      "yuzu_version": "4176",
      "yuzu_firmware": "17.0.1",
      "branch": "ea"
    }
  },
  "ryujinx_history": {
    "E:\\app\\ryujinx": {
      "path": "E:\\app\\ryujinx",
      "version": "1.1.1217",
      "firmware": "17.0.1",
      "branch": "ava"
    },
    "E:\\app\\ryujinx_old": {
      "path": "E:\\app\\ryujinx_old",
      "version": "1.1.1217",
      "firmware": "17.0.1",
      "branch": "mainline"
    }
  },
  "yuzu_save_backup_path": "D:\\yuzu_save_backup"
}

**Comment by RUANRUI1995** [comment]
另外从1217版本开始AVA和正式版已经合并了，安装包都一样了
https://github.com/Ryujinx/Ryujinx/wiki/Changelog#111216-111217---2024-03-02

**Comment by triwinds** [comment]
Fixed in 0.4.7
