### ISSUE TITLE
yuzu已经没有了，听说有suzu和nuzu，能不能同步一下

### ISSUE THREAD

**Issue by 660660660660** [triwinds/ns-emu-tools#99]
请在描述问题的同时上传 ns-emu-tools.log 这个文件。
如果问题与 aria2 下载有关，请将 aria2.log 这个文件也带上。
(将文件拖拽至输入框内即可)

**Comment by RUANRUI1995** [comment]
nuzu也没了，现在yuzu ea版还是在的

**Comment by Rulessly** [comment]
suyu还有，在gitlab

**Comment by triwinds** [comment]
Duplicate (#103)
